// <auto-generated />
using Lumini.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lumini.Infrastructure.Migrations
{
    [DbContext(typeof(LuminiDbContext))]
    partial class LuminiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("Lumini.Domain.Entities.Route", b =>
                {
                    b.Property<string>("Origin")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Origin", "Destination");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Origin = "GRU",
                            Destination = "BRC",
                            Value = 10m
                        },
                        new
                        {
                            Origin = "BRC",
                            Destination = "SCL",
                            Value = 5m
                        },
                        new
                        {
                            Origin = "GRU",
                            Destination = "CDG",
                            Value = 75m
                        },
                        new
                        {
                            Origin = "GRU",
                            Destination = "SCL",
                            Value = 20m
                        },
                        new
                        {
                            Origin = "GRU",
                            Destination = "ORL",
                            Value = 56m
                        },
                        new
                        {
                            Origin = "ORL",
                            Destination = "CDG",
                            Value = 5m
                        },
                        new
                        {
                            Origin = "SCL",
                            Destination = "ORL",
                            Value = 20m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
